name: Build and Publish CO-DETR Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: tnodecode
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  IMAGE_NAME: spine-co-detr

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Build Docker image
        run: docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME .

      - name: Push Docker image to Docker Hub
        run: docker push $DOCKERHUB_USERNAME/$IMAGE_NAME

      - name: Logout from Docker Hub
        run: docker logout